"""empty message

Revision ID: b3a3e650b7c7
Revises: a5cffa318ac2
Create Date: 2024-11-09 17:28:01.542015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a3e650b7c7'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('altura', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('url_info', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('planetas',
    sa.Column('id_planeta', sa.Integer(), nullable=False),
    sa.Column('nombre_planeta', sa.String(length=50), nullable=False),
    sa.Column('diametro_planeta', sa.Integer(), nullable=False),
    sa.Column('clima_planeta', sa.String(length=50), nullable=False),
    sa.Column('poblacion_planeta', sa.String(), nullable=False),
    sa.Column('url_info', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_planeta')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('clave_acceso', sa.String(length=80), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('favoritos_personas',
    sa.Column('id_favorito', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['personas.id_persona'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_favorito')
    )
    op.create_table('favoritos_planetas',
    sa.Column('id_favorito', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_planeta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_planeta'], ['planetas.id_planeta'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_favorito')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('favoritos_planetas')
    op.drop_table('favoritos_personas')
    op.drop_table('usuarios')
    op.drop_table('planetas')
    op.drop_table('personas')
    # ### end Alembic commands ###
